//! The snake customization catalog: every head and tail cosmetic, as
//! types. Extracted 2026-07-04 from play's authoritative
//! `data_load_snake_customizations` management command.
//!
//! This file is the source of truth going forward. To add a cosmetic:
//! add an enum variant — the compiler walks you through the match arms.
#![allow(clippy::too_many_lines)]

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Availability {
    /// Free for all, no grant needed.
    Everyone,
    /// Needs a grant unless the entry's cost is 0.
    Restricted,
    /// Not shown in UI; grant-only.
    Hidden,
    /// Shown in UI but grant-only.
    Preview,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Group {
    Standard,
    PartnerBrands,
    Community,
    SpecialEdition,
    Collection2024,
    Collection2023,
    Collection2022,
    Collection2021,
    Collection2020,
    Collection2019,
}

impl Group {
    /// Display order for the browse page.
    pub const ALL: &[Group] = &[
        Group::Standard,
        Group::PartnerBrands,
        Group::Community,
        Group::SpecialEdition,
        Group::Collection2024,
        Group::Collection2023,
        Group::Collection2022,
        Group::Collection2021,
        Group::Collection2020,
        Group::Collection2019,
    ];

    pub fn title(self) -> &'static str {
        match self {
            Group::Standard => "Standard",
            Group::PartnerBrands => "Partner Brands",
            Group::Community => "Community",
            Group::SpecialEdition => "Special Edition",
            Group::Collection2024 => "2024 Collection",
            Group::Collection2023 => "2023 Collection",
            Group::Collection2022 => "2022 Collection",
            Group::Collection2021 => "2021 Collection",
            Group::Collection2020 => "2020 Collection",
            Group::Collection2019 => "2019 Collection",
        }
    }

    pub fn availability(self) -> Availability {
        match self {
            Group::Standard => Availability::Everyone,
            Group::PartnerBrands => Availability::Everyone,
            Group::Community => Availability::Restricted,
            Group::SpecialEdition => Availability::Hidden,
            Group::Collection2024 => Availability::Hidden,
            Group::Collection2023 => Availability::Restricted,
            Group::Collection2022 => Availability::Restricted,
            Group::Collection2021 => Availability::Restricted,
            Group::Collection2020 => Availability::Restricted,
            Group::Collection2019 => Availability::Everyone,
        }
    }
}

/// Static metadata for one catalog entry.
#[derive(Debug, Clone, Copy)]
pub struct CustomizationDef {
    pub display_name: &'static str,
    pub description: &'static str,
    pub group: Group,
    /// Battlesnake Points price on play; the economy is not live in
    /// arena, so this only distinguishes restricted-free (0) from
    /// grant-required (> 0).
    pub cost: u32,
    /// Set only where the asset URL deviates from the slug convention.
    pub image_override: Option<&'static str>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Head {
    Default,
    Beluga,
    Bendr,
    Dead,
    Evil,
    Fang,
    Pixel,
    Safe,
    SandWorm,
    Shades,
    Silly,
    Smile,
    Tongue,
    DoSammy,
    RbcBowler,
    ReplitMark,
    MlhGene,
    NrRocket,
    AllSeeing,
    SmartCaterpillar,
    TransRightsScarf,
    CrystalPower,
    CosmicHorror,
    BeachPuffin,
    Pirate,
    CosmicHorrorSpecial,
    BeachPuffinSpecial,
    Hydra,
    PirateSpecial,
    Fish,
    PruzzeSpecial,
    Turtle,
    Judge,
    Monkey,
    Subway,
    Frog,
    Antelope,
    Glasses,
    Rose,
    Bird,
    Chicken,
    Egg,
    PopStar,
    Singer,
    Ferret,
    Flytrap,
    Submarine,
    Baseball,
    Bee,
    Horse,
    Chef,
    Ladybug,
    Pig,
    Guitar,
    Train,
    Duck,
    Ghost,
    Knight,
    Superhero,
    TopHat,
    Cat,
    Drill,
    Bull,
    Queen,
    Eel,
    Shark,
    Sleepy,
    Dragon,
    CuteDragon,
    Chomp,
    Orca,
    PixelRound,
    Sneaky,
    Villain,
    Viper,
    Happy,
    Whale,
    Alligator,
    Comet,
    Football,
    Iguana,
    LanternFish,
    Mask,
    Missile,
    MotoHelmet,
    Moustache,
    RocketHelmet,
    Snail,
    SpaceHelmet,
    Caffeine,
    Gamer,
    TigerKing,
    Workout,
    Jackolantern,
    Pumpkin,
    Bonhomme,
    Earmuffs,
    Rudolph,
    Scarf,
    Ski,
    Snowman,
    SnowWorm,
}

impl Head {
    pub const KIND: &str = "head";

    pub const ALL: &[Head] = &[
        Head::Default,
        Head::Beluga,
        Head::Bendr,
        Head::Dead,
        Head::Evil,
        Head::Fang,
        Head::Pixel,
        Head::Safe,
        Head::SandWorm,
        Head::Shades,
        Head::Silly,
        Head::Smile,
        Head::Tongue,
        Head::DoSammy,
        Head::RbcBowler,
        Head::ReplitMark,
        Head::MlhGene,
        Head::NrRocket,
        Head::AllSeeing,
        Head::SmartCaterpillar,
        Head::TransRightsScarf,
        Head::CrystalPower,
        Head::CosmicHorror,
        Head::BeachPuffin,
        Head::Pirate,
        Head::CosmicHorrorSpecial,
        Head::BeachPuffinSpecial,
        Head::Hydra,
        Head::PirateSpecial,
        Head::Fish,
        Head::PruzzeSpecial,
        Head::Turtle,
        Head::Judge,
        Head::Monkey,
        Head::Subway,
        Head::Frog,
        Head::Antelope,
        Head::Glasses,
        Head::Rose,
        Head::Bird,
        Head::Chicken,
        Head::Egg,
        Head::PopStar,
        Head::Singer,
        Head::Ferret,
        Head::Flytrap,
        Head::Submarine,
        Head::Baseball,
        Head::Bee,
        Head::Horse,
        Head::Chef,
        Head::Ladybug,
        Head::Pig,
        Head::Guitar,
        Head::Train,
        Head::Duck,
        Head::Ghost,
        Head::Knight,
        Head::Superhero,
        Head::TopHat,
        Head::Cat,
        Head::Drill,
        Head::Bull,
        Head::Queen,
        Head::Eel,
        Head::Shark,
        Head::Sleepy,
        Head::Dragon,
        Head::CuteDragon,
        Head::Chomp,
        Head::Orca,
        Head::PixelRound,
        Head::Sneaky,
        Head::Villain,
        Head::Viper,
        Head::Happy,
        Head::Whale,
        Head::Alligator,
        Head::Comet,
        Head::Football,
        Head::Iguana,
        Head::LanternFish,
        Head::Mask,
        Head::Missile,
        Head::MotoHelmet,
        Head::Moustache,
        Head::RocketHelmet,
        Head::Snail,
        Head::SpaceHelmet,
        Head::Caffeine,
        Head::Gamer,
        Head::TigerKing,
        Head::Workout,
        Head::Jackolantern,
        Head::Pumpkin,
        Head::Bonhomme,
        Head::Earmuffs,
        Head::Rudolph,
        Head::Scarf,
        Head::Ski,
        Head::Snowman,
        Head::SnowWorm,
    ];

    pub fn slug(self) -> &'static str {
        match self {
            Head::Default => "default",
            Head::Beluga => "beluga",
            Head::Bendr => "bendr",
            Head::Dead => "dead",
            Head::Evil => "evil",
            Head::Fang => "fang",
            Head::Pixel => "pixel",
            Head::Safe => "safe",
            Head::SandWorm => "sand-worm",
            Head::Shades => "shades",
            Head::Silly => "silly",
            Head::Smile => "smile",
            Head::Tongue => "tongue",
            Head::DoSammy => "do-sammy",
            Head::RbcBowler => "rbc-bowler",
            Head::ReplitMark => "replit-mark",
            Head::MlhGene => "mlh-gene",
            Head::NrRocket => "nr-rocket",
            Head::AllSeeing => "all-seeing",
            Head::SmartCaterpillar => "smart-caterpillar",
            Head::TransRightsScarf => "trans-rights-scarf",
            Head::CrystalPower => "crystal-power",
            Head::CosmicHorror => "cosmic-horror",
            Head::BeachPuffin => "beach-puffin",
            Head::Pirate => "pirate",
            Head::CosmicHorrorSpecial => "cosmic-horror-special",
            Head::BeachPuffinSpecial => "beach-puffin-special",
            Head::Hydra => "hydra",
            Head::PirateSpecial => "pirate-special",
            Head::Fish => "fish",
            Head::PruzzeSpecial => "pruzze-special",
            Head::Turtle => "turtle",
            Head::Judge => "judge",
            Head::Monkey => "monkey",
            Head::Subway => "subway",
            Head::Frog => "frog",
            Head::Antelope => "antelope",
            Head::Glasses => "glasses",
            Head::Rose => "rose",
            Head::Bird => "bird",
            Head::Chicken => "chicken",
            Head::Egg => "egg",
            Head::PopStar => "pop-star",
            Head::Singer => "singer",
            Head::Ferret => "ferret",
            Head::Flytrap => "flytrap",
            Head::Submarine => "submarine",
            Head::Baseball => "baseball",
            Head::Bee => "bee",
            Head::Horse => "horse",
            Head::Chef => "chef",
            Head::Ladybug => "ladybug",
            Head::Pig => "pig",
            Head::Guitar => "guitar",
            Head::Train => "train",
            Head::Duck => "duck",
            Head::Ghost => "ghost",
            Head::Knight => "knight",
            Head::Superhero => "superhero",
            Head::TopHat => "top-hat",
            Head::Cat => "cat",
            Head::Drill => "drill",
            Head::Bull => "bull",
            Head::Queen => "queen",
            Head::Eel => "eel",
            Head::Shark => "shark",
            Head::Sleepy => "sleepy",
            Head::Dragon => "dragon",
            Head::CuteDragon => "cute-dragon",
            Head::Chomp => "chomp",
            Head::Orca => "orca",
            Head::PixelRound => "pixel-round",
            Head::Sneaky => "sneaky",
            Head::Villain => "villain",
            Head::Viper => "viper",
            Head::Happy => "happy",
            Head::Whale => "whale",
            Head::Alligator => "alligator",
            Head::Comet => "comet",
            Head::Football => "football",
            Head::Iguana => "iguana",
            Head::LanternFish => "lantern-fish",
            Head::Mask => "mask",
            Head::Missile => "missile",
            Head::MotoHelmet => "moto-helmet",
            Head::Moustache => "moustache",
            Head::RocketHelmet => "rocket-helmet",
            Head::Snail => "snail",
            Head::SpaceHelmet => "space-helmet",
            Head::Caffeine => "caffeine",
            Head::Gamer => "gamer",
            Head::TigerKing => "tiger-king",
            Head::Workout => "workout",
            Head::Jackolantern => "jackolantern",
            Head::Pumpkin => "pumpkin",
            Head::Bonhomme => "bonhomme",
            Head::Earmuffs => "earmuffs",
            Head::Rudolph => "rudolph",
            Head::Scarf => "scarf",
            Head::Ski => "ski",
            Head::Snowman => "snowman",
            Head::SnowWorm => "snow-worm",
        }
    }

    pub fn from_slug(slug: &str) -> Option<Self> {
        Some(match slug {
            "default" => Head::Default,
            "beluga" => Head::Beluga,
            "bendr" => Head::Bendr,
            "dead" => Head::Dead,
            "evil" => Head::Evil,
            "fang" => Head::Fang,
            "pixel" => Head::Pixel,
            "safe" => Head::Safe,
            "sand-worm" => Head::SandWorm,
            "shades" => Head::Shades,
            "silly" => Head::Silly,
            "smile" => Head::Smile,
            "tongue" => Head::Tongue,
            "do-sammy" => Head::DoSammy,
            "rbc-bowler" => Head::RbcBowler,
            "replit-mark" => Head::ReplitMark,
            "mlh-gene" => Head::MlhGene,
            "nr-rocket" => Head::NrRocket,
            "all-seeing" => Head::AllSeeing,
            "smart-caterpillar" => Head::SmartCaterpillar,
            "trans-rights-scarf" => Head::TransRightsScarf,
            "crystal-power" => Head::CrystalPower,
            "cosmic-horror" => Head::CosmicHorror,
            "beach-puffin" => Head::BeachPuffin,
            "pirate" => Head::Pirate,
            "cosmic-horror-special" => Head::CosmicHorrorSpecial,
            "beach-puffin-special" => Head::BeachPuffinSpecial,
            "hydra" => Head::Hydra,
            "pirate-special" => Head::PirateSpecial,
            "fish" => Head::Fish,
            "pruzze-special" => Head::PruzzeSpecial,
            "turtle" => Head::Turtle,
            "judge" => Head::Judge,
            "monkey" => Head::Monkey,
            "subway" => Head::Subway,
            "frog" => Head::Frog,
            "antelope" => Head::Antelope,
            "glasses" => Head::Glasses,
            "rose" => Head::Rose,
            "bird" => Head::Bird,
            "chicken" => Head::Chicken,
            "egg" => Head::Egg,
            "pop-star" => Head::PopStar,
            "singer" => Head::Singer,
            "ferret" => Head::Ferret,
            "flytrap" => Head::Flytrap,
            "submarine" => Head::Submarine,
            "baseball" => Head::Baseball,
            "bee" => Head::Bee,
            "horse" => Head::Horse,
            "chef" => Head::Chef,
            "ladybug" => Head::Ladybug,
            "pig" => Head::Pig,
            "guitar" => Head::Guitar,
            "train" => Head::Train,
            "duck" => Head::Duck,
            "ghost" => Head::Ghost,
            "knight" => Head::Knight,
            "superhero" => Head::Superhero,
            "top-hat" => Head::TopHat,
            "cat" => Head::Cat,
            "drill" => Head::Drill,
            "bull" => Head::Bull,
            "queen" => Head::Queen,
            "eel" => Head::Eel,
            "shark" => Head::Shark,
            "sleepy" => Head::Sleepy,
            "dragon" => Head::Dragon,
            "cute-dragon" => Head::CuteDragon,
            "chomp" => Head::Chomp,
            "orca" => Head::Orca,
            "pixel-round" => Head::PixelRound,
            "sneaky" => Head::Sneaky,
            "villain" => Head::Villain,
            "viper" => Head::Viper,
            "happy" => Head::Happy,
            "whale" => Head::Whale,
            "alligator" => Head::Alligator,
            "comet" => Head::Comet,
            "football" => Head::Football,
            "iguana" => Head::Iguana,
            "lantern-fish" => Head::LanternFish,
            "mask" => Head::Mask,
            "missile" => Head::Missile,
            "moto-helmet" => Head::MotoHelmet,
            "moustache" => Head::Moustache,
            "rocket-helmet" => Head::RocketHelmet,
            "snail" => Head::Snail,
            "space-helmet" => Head::SpaceHelmet,
            "caffeine" => Head::Caffeine,
            "gamer" => Head::Gamer,
            "tiger-king" => Head::TigerKing,
            "workout" => Head::Workout,
            "jackolantern" => Head::Jackolantern,
            "pumpkin" => Head::Pumpkin,
            "bonhomme" => Head::Bonhomme,
            "earmuffs" => Head::Earmuffs,
            "rudolph" => Head::Rudolph,
            "scarf" => Head::Scarf,
            "ski" => Head::Ski,
            "snowman" => Head::Snowman,
            "snow-worm" => Head::SnowWorm,
            _ => return None,
        })
    }

    pub fn def(self) -> CustomizationDef {
        match self {
            Head::Default => CustomizationDef {
                display_name: "Default",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Beluga => CustomizationDef {
                display_name: "Beluga",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Bendr => CustomizationDef {
                display_name: "Bendr",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Dead => CustomizationDef {
                display_name: "Dead",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Evil => CustomizationDef {
                display_name: "Evil",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Fang => CustomizationDef {
                display_name: "Fang",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Pixel => CustomizationDef {
                display_name: "Pixel",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Safe => CustomizationDef {
                display_name: "Safe",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::SandWorm => CustomizationDef {
                display_name: "Sand Worm",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Shades => CustomizationDef {
                display_name: "Shades",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Silly => CustomizationDef {
                display_name: "Silly",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Smile => CustomizationDef {
                display_name: "Smile",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::Tongue => CustomizationDef {
                display_name: "Tongue",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Head::DoSammy => CustomizationDef {
                display_name: "DigitalOcean Sammy",
                description: "Provided by DigitalOcean for the 2022 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Head::RbcBowler => CustomizationDef {
                display_name: "RBC Bowler Hat",
                description: "Provided by RBC for the 2021 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Head::ReplitMark => CustomizationDef {
                display_name: "Replit Mark",
                description: "Provided by Replit.com for the 2021 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Head::MlhGene => CustomizationDef {
                display_name: "MLH",
                description: "Provided by Major League Hacking for the 2022 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Head::NrRocket => CustomizationDef {
                display_name: "New Relic Rocket Capsule",
                description: "Provided by New Relic for the 2022 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Head::AllSeeing => CustomizationDef {
                display_name: "House of Aileen's Magic Eye",
                description: "Created when the House of Aileen won the 2021 Summer Caster Crown tournament",
                group: Group::Community,
                cost: 0,
                image_override: None,
            },
            Head::SmartCaterpillar => CustomizationDef {
                display_name: "Smart Caterpillar",
                description: "Created for user Butterfy 🦋 Tamer for winning the Summer League 2022 People's Choice Award",
                group: Group::Community,
                cost: 0,
                image_override: None,
            },
            Head::TransRightsScarf => CustomizationDef {
                display_name: "Trans Rights Scarf",
                description: "Created for user penelopezone for winning the Fall League 2022 People's Choice Award",
                group: Group::Community,
                cost: 0,
                image_override: None,
            },
            Head::CrystalPower => CustomizationDef {
                display_name: "Crystal Power",
                description: "Created after the House of Aileen won the 2021 Fall Casters Crown tournament",
                group: Group::Community,
                cost: 200,
                image_override: None,
            },
            Head::CosmicHorror => CustomizationDef {
                display_name: "Cosmic Horror",
                description: "Created for JonathanArns for winning the Spring Caster Cup 2022 tournament",
                group: Group::Community,
                cost: 200,
                image_override: None,
            },
            Head::BeachPuffin => CustomizationDef {
                display_name: "Puffin",
                description: "Created for coreya for winning the Spring League 2022 People's Choice Award",
                group: Group::Community,
                cost: 200,
                image_override: None,
            },
            Head::Pirate => CustomizationDef {
                display_name: "Pirate",
                description: "Created for jlafayette for winning the Summer League 2022 People's Choice Award!",
                group: Group::Community,
                cost: 200,
                image_override: None,
            },
            Head::CosmicHorrorSpecial => CustomizationDef {
                display_name: "Cosmic Horror - Special Edition",
                description: "Created for jonathanarns for winning the 2022 Spring Caster Cup tournament",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Head::BeachPuffinSpecial => CustomizationDef {
                display_name: "Puffin - Special Edition",
                description: "Created for coreya for winning the Spring League 2022 People's Choice Award",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Head::Hydra => CustomizationDef {
                display_name: "Community Hydra",
                description: "Created for anyone who is a recognized Community Contributor to the Battlesnake ecosystem",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Head::PirateSpecial => CustomizationDef {
                display_name: "Pirate - Special Edition",
                description: "Created for jlafayette for winning the Summer League 2022 People's Choice Award!",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Head::Fish => CustomizationDef {
                display_name: "Fish",
                description: "",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Head::PruzzeSpecial => CustomizationDef {
                display_name: "Prüzze Gamer - Special Edition",
                description: "Created for Prüzze as a thank you for being a long term Battlesnake competitor!",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: Some(
                    "https://media.battlesnake.com/snakes/heads/pirate-special.svg",
                ),
            },
            Head::Turtle => CustomizationDef {
                display_name: "Turtle",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Head::Judge => CustomizationDef {
                display_name: "Judge",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Head::Monkey => CustomizationDef {
                display_name: "Monkey",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Head::Subway => CustomizationDef {
                display_name: "Subway",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Head::Frog => CustomizationDef {
                display_name: "Frog",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Head::Antelope => CustomizationDef {
                display_name: "Antelope",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Glasses => CustomizationDef {
                display_name: "Glasses",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Rose => CustomizationDef {
                display_name: "Rose",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Bird => CustomizationDef {
                display_name: "Bird",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Chicken => CustomizationDef {
                display_name: "Chicken",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Egg => CustomizationDef {
                display_name: "Egg",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::PopStar => CustomizationDef {
                display_name: "Pop-Star",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Singer => CustomizationDef {
                display_name: "Singer",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Ferret => CustomizationDef {
                display_name: "Ferret",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Flytrap => CustomizationDef {
                display_name: "Flytrap",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Submarine => CustomizationDef {
                display_name: "Submarine",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Baseball => CustomizationDef {
                display_name: "Baseball",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Bee => CustomizationDef {
                display_name: "Bee",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Horse => CustomizationDef {
                display_name: "Horse",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Chef => CustomizationDef {
                display_name: "Chef",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Ladybug => CustomizationDef {
                display_name: "Ladybug",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Pig => CustomizationDef {
                display_name: "Pig",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Guitar => CustomizationDef {
                display_name: "Guitar",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Train => CustomizationDef {
                display_name: "Train",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Duck => CustomizationDef {
                display_name: "Duck",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Ghost => CustomizationDef {
                display_name: "Ghost",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Knight => CustomizationDef {
                display_name: "Knight",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Superhero => CustomizationDef {
                display_name: "Superhero",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::TopHat => CustomizationDef {
                display_name: "Top Hat",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Cat => CustomizationDef {
                display_name: "Cat",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Drill => CustomizationDef {
                display_name: "Drill",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Bull => CustomizationDef {
                display_name: "Bull",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Queen => CustomizationDef {
                display_name: "Queen",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Head::Eel => CustomizationDef {
                display_name: "Eel",
                description: "Released June 2022",
                group: Group::Collection2022,
                cost: 200,
                image_override: None,
            },
            Head::Shark => CustomizationDef {
                display_name: "Shark",
                description: "Released June 2022",
                group: Group::Collection2022,
                cost: 200,
                image_override: None,
            },
            Head::Sleepy => CustomizationDef {
                display_name: "Sleepy",
                description: "Released June 2022",
                group: Group::Collection2022,
                cost: 200,
                image_override: None,
            },
            Head::Dragon => CustomizationDef {
                display_name: "Dragon",
                description: "Released September 2022",
                group: Group::Collection2022,
                cost: 200,
                image_override: None,
            },
            Head::CuteDragon => CustomizationDef {
                display_name: "Cute-Dragon",
                description: "Released September 2022",
                group: Group::Collection2022,
                cost: 200,
                image_override: None,
            },
            Head::Chomp => CustomizationDef {
                display_name: "Chomp",
                description: "Released for Spring League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Orca => CustomizationDef {
                display_name: "Orca",
                description: "Released for Spring League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::PixelRound => CustomizationDef {
                display_name: "Pixel Round",
                description: "Released for Spring League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Sneaky => CustomizationDef {
                display_name: "Sneaky",
                description: "Released for Spring League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Villain => CustomizationDef {
                display_name: "Villain",
                description: "Released for Summer League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Viper => CustomizationDef {
                display_name: "Viper",
                description: "Released for Summer League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: Some("https://media.battlesnake.com/snakes/heads/rattler.svg"),
            },
            Head::Happy => CustomizationDef {
                display_name: "Happy",
                description: "Released for Fall League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Whale => CustomizationDef {
                display_name: "Whale",
                description: "Released for Fall League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Alligator => CustomizationDef {
                display_name: "Alligator",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Comet => CustomizationDef {
                display_name: "Comet",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Football => CustomizationDef {
                display_name: "Football",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Iguana => CustomizationDef {
                display_name: "Iguana",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::LanternFish => CustomizationDef {
                display_name: "Lantern Fish",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Mask => CustomizationDef {
                display_name: "Mask",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Missile => CustomizationDef {
                display_name: "Missile",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::MotoHelmet => CustomizationDef {
                display_name: "Moto Helmet",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Moustache => CustomizationDef {
                display_name: "Moustache",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::RocketHelmet => CustomizationDef {
                display_name: "Rocket Helmet",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Snail => CustomizationDef {
                display_name: "Snail",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::SpaceHelmet => CustomizationDef {
                display_name: "Space Helmet",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Head::Caffeine => CustomizationDef {
                display_name: "Caffeine",
                description: "Released for the Stay Home and Code 2020 compeition",
                group: Group::Collection2020,
                cost: 0,
                image_override: None,
            },
            Head::Gamer => CustomizationDef {
                display_name: "Gamer",
                description: "Released for the Stay Home and Code 2020 compeition",
                group: Group::Collection2020,
                cost: 0,
                image_override: None,
            },
            Head::TigerKing => CustomizationDef {
                display_name: "Tiger King",
                description: "Released for the Stay Home and Code 2020 compeition",
                group: Group::Collection2020,
                cost: 0,
                image_override: None,
            },
            Head::Workout => CustomizationDef {
                display_name: "Workout",
                description: "Released for the Stay Home and Code 2020 compeition",
                group: Group::Collection2020,
                cost: 0,
                image_override: None,
            },
            Head::Jackolantern => CustomizationDef {
                display_name: "Jack O'lantern",
                description: "Released for Fall League 2020",
                group: Group::Collection2020,
                cost: 100,
                image_override: None,
            },
            Head::Pumpkin => CustomizationDef {
                display_name: "Pumpkin",
                description: "Released for Fall League 2020",
                group: Group::Collection2020,
                cost: 100,
                image_override: None,
            },
            Head::Bonhomme => CustomizationDef {
                display_name: "Bonhomme",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Head::Earmuffs => CustomizationDef {
                display_name: "Earmuffs",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Head::Rudolph => CustomizationDef {
                display_name: "Rudolph",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Head::Scarf => CustomizationDef {
                display_name: "Scarf",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Head::Ski => CustomizationDef {
                display_name: "Ski",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Head::Snowman => CustomizationDef {
                display_name: "Snowman",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Head::SnowWorm => CustomizationDef {
                display_name: "Snow Worm",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
        }
    }
}

// Variant names mirror slugs exactly (tiger-tail -> TigerTail), even
// where that trips clippy's enum_variant_names.
#[allow(clippy::enum_variant_names)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Tail {
    Default,
    BlockBum,
    Bolt,
    Curled,
    FatRattle,
    Freckled,
    Hook,
    Pixel,
    RoundBum,
    Sharp,
    Skinny,
    SmallRattle,
    DoSammy,
    RbcNecktie,
    ReplitNotmark,
    MlhGene,
    NrBooster,
    MysticMoon,
    CrystalPower,
    CosmicHorror,
    BeachPuffin,
    Pirate,
    BeachPuffinSpecial,
    Hydra,
    PirateSpecial,
    Goldfish,
    PruzzeSpecial,
    Turtle,
    Judge,
    Monkey,
    Subway,
    Antelope,
    Rose,
    Chicken,
    Egg,
    PopStar,
    Ferret,
    Flytrap,
    Submarine,
    Bee,
    Horse,
    Chef,
    Ladybug,
    Pig,
    Guitar,
    Train,
    Duck,
    Cat,
    Gauge,
    Bull,
    Queen,
    Nightcap,
    Wave,
    Dragon,
    Ghost,
    PixelRound,
    Swirl,
    Swoop,
    Rattle,
    Rocket,
    Offroad,
    Shiny,
    Alligator,
    Comet,
    Fish,
    Flame,
    Football,
    Iguana,
    Ion,
    Missile,
    SkinnyJeans,
    Snail,
    Tire,
    Virus,
    Coffee,
    Mouse,
    TigerTail,
    Weight,
    Leaf,
    Pumpkin,
    Bonhomme,
    Flake,
    IceSkate,
    Present,
}

impl Tail {
    pub const KIND: &str = "tail";

    pub const ALL: &[Tail] = &[
        Tail::Default,
        Tail::BlockBum,
        Tail::Bolt,
        Tail::Curled,
        Tail::FatRattle,
        Tail::Freckled,
        Tail::Hook,
        Tail::Pixel,
        Tail::RoundBum,
        Tail::Sharp,
        Tail::Skinny,
        Tail::SmallRattle,
        Tail::DoSammy,
        Tail::RbcNecktie,
        Tail::ReplitNotmark,
        Tail::MlhGene,
        Tail::NrBooster,
        Tail::MysticMoon,
        Tail::CrystalPower,
        Tail::CosmicHorror,
        Tail::BeachPuffin,
        Tail::Pirate,
        Tail::BeachPuffinSpecial,
        Tail::Hydra,
        Tail::PirateSpecial,
        Tail::Goldfish,
        Tail::PruzzeSpecial,
        Tail::Turtle,
        Tail::Judge,
        Tail::Monkey,
        Tail::Subway,
        Tail::Antelope,
        Tail::Rose,
        Tail::Chicken,
        Tail::Egg,
        Tail::PopStar,
        Tail::Ferret,
        Tail::Flytrap,
        Tail::Submarine,
        Tail::Bee,
        Tail::Horse,
        Tail::Chef,
        Tail::Ladybug,
        Tail::Pig,
        Tail::Guitar,
        Tail::Train,
        Tail::Duck,
        Tail::Cat,
        Tail::Gauge,
        Tail::Bull,
        Tail::Queen,
        Tail::Nightcap,
        Tail::Wave,
        Tail::Dragon,
        Tail::Ghost,
        Tail::PixelRound,
        Tail::Swirl,
        Tail::Swoop,
        Tail::Rattle,
        Tail::Rocket,
        Tail::Offroad,
        Tail::Shiny,
        Tail::Alligator,
        Tail::Comet,
        Tail::Fish,
        Tail::Flame,
        Tail::Football,
        Tail::Iguana,
        Tail::Ion,
        Tail::Missile,
        Tail::SkinnyJeans,
        Tail::Snail,
        Tail::Tire,
        Tail::Virus,
        Tail::Coffee,
        Tail::Mouse,
        Tail::TigerTail,
        Tail::Weight,
        Tail::Leaf,
        Tail::Pumpkin,
        Tail::Bonhomme,
        Tail::Flake,
        Tail::IceSkate,
        Tail::Present,
    ];

    pub fn slug(self) -> &'static str {
        match self {
            Tail::Default => "default",
            Tail::BlockBum => "block-bum",
            Tail::Bolt => "bolt",
            Tail::Curled => "curled",
            Tail::FatRattle => "fat-rattle",
            Tail::Freckled => "freckled",
            Tail::Hook => "hook",
            Tail::Pixel => "pixel",
            Tail::RoundBum => "round-bum",
            Tail::Sharp => "sharp",
            Tail::Skinny => "skinny",
            Tail::SmallRattle => "small-rattle",
            Tail::DoSammy => "do-sammy",
            Tail::RbcNecktie => "rbc-necktie",
            Tail::ReplitNotmark => "replit-notmark",
            Tail::MlhGene => "mlh-gene",
            Tail::NrBooster => "nr-booster",
            Tail::MysticMoon => "mystic-moon",
            Tail::CrystalPower => "crystal-power",
            Tail::CosmicHorror => "cosmic-horror",
            Tail::BeachPuffin => "beach-puffin",
            Tail::Pirate => "pirate",
            Tail::BeachPuffinSpecial => "beach-puffin-special",
            Tail::Hydra => "hydra",
            Tail::PirateSpecial => "pirate-special",
            Tail::Goldfish => "goldfish",
            Tail::PruzzeSpecial => "pruzze-special",
            Tail::Turtle => "turtle",
            Tail::Judge => "judge",
            Tail::Monkey => "monkey",
            Tail::Subway => "subway",
            Tail::Antelope => "antelope",
            Tail::Rose => "rose",
            Tail::Chicken => "chicken",
            Tail::Egg => "egg",
            Tail::PopStar => "pop-star",
            Tail::Ferret => "ferret",
            Tail::Flytrap => "flytrap",
            Tail::Submarine => "submarine",
            Tail::Bee => "bee",
            Tail::Horse => "horse",
            Tail::Chef => "chef",
            Tail::Ladybug => "ladybug",
            Tail::Pig => "pig",
            Tail::Guitar => "guitar",
            Tail::Train => "train",
            Tail::Duck => "duck",
            Tail::Cat => "cat",
            Tail::Gauge => "gauge",
            Tail::Bull => "bull",
            Tail::Queen => "queen",
            Tail::Nightcap => "nightcap",
            Tail::Wave => "wave",
            Tail::Dragon => "dragon",
            Tail::Ghost => "ghost",
            Tail::PixelRound => "pixel-round",
            Tail::Swirl => "swirl",
            Tail::Swoop => "swoop",
            Tail::Rattle => "rattle",
            Tail::Rocket => "rocket",
            Tail::Offroad => "offroad",
            Tail::Shiny => "shiny",
            Tail::Alligator => "alligator",
            Tail::Comet => "comet",
            Tail::Fish => "fish",
            Tail::Flame => "flame",
            Tail::Football => "football",
            Tail::Iguana => "iguana",
            Tail::Ion => "ion",
            Tail::Missile => "missile",
            Tail::SkinnyJeans => "skinny-jeans",
            Tail::Snail => "snail",
            Tail::Tire => "tire",
            Tail::Virus => "virus",
            Tail::Coffee => "coffee",
            Tail::Mouse => "mouse",
            Tail::TigerTail => "tiger-tail",
            Tail::Weight => "weight",
            Tail::Leaf => "leaf",
            Tail::Pumpkin => "pumpkin",
            Tail::Bonhomme => "bonhomme",
            Tail::Flake => "flake",
            Tail::IceSkate => "ice-skate",
            Tail::Present => "present",
        }
    }

    pub fn from_slug(slug: &str) -> Option<Self> {
        Some(match slug {
            "default" => Tail::Default,
            "block-bum" => Tail::BlockBum,
            "bolt" => Tail::Bolt,
            "curled" => Tail::Curled,
            "fat-rattle" => Tail::FatRattle,
            "freckled" => Tail::Freckled,
            "hook" => Tail::Hook,
            "pixel" => Tail::Pixel,
            "round-bum" => Tail::RoundBum,
            "sharp" => Tail::Sharp,
            "skinny" => Tail::Skinny,
            "small-rattle" => Tail::SmallRattle,
            "do-sammy" => Tail::DoSammy,
            "rbc-necktie" => Tail::RbcNecktie,
            "replit-notmark" => Tail::ReplitNotmark,
            "mlh-gene" => Tail::MlhGene,
            "nr-booster" => Tail::NrBooster,
            "mystic-moon" => Tail::MysticMoon,
            "crystal-power" => Tail::CrystalPower,
            "cosmic-horror" => Tail::CosmicHorror,
            "beach-puffin" => Tail::BeachPuffin,
            "pirate" => Tail::Pirate,
            "beach-puffin-special" => Tail::BeachPuffinSpecial,
            "hydra" => Tail::Hydra,
            "pirate-special" => Tail::PirateSpecial,
            "goldfish" => Tail::Goldfish,
            "pruzze-special" => Tail::PruzzeSpecial,
            "turtle" => Tail::Turtle,
            "judge" => Tail::Judge,
            "monkey" => Tail::Monkey,
            "subway" => Tail::Subway,
            "antelope" => Tail::Antelope,
            "rose" => Tail::Rose,
            "chicken" => Tail::Chicken,
            "egg" => Tail::Egg,
            "pop-star" => Tail::PopStar,
            "ferret" => Tail::Ferret,
            "flytrap" => Tail::Flytrap,
            "submarine" => Tail::Submarine,
            "bee" => Tail::Bee,
            "horse" => Tail::Horse,
            "chef" => Tail::Chef,
            "ladybug" => Tail::Ladybug,
            "pig" => Tail::Pig,
            "guitar" => Tail::Guitar,
            "train" => Tail::Train,
            "duck" => Tail::Duck,
            "cat" => Tail::Cat,
            "gauge" => Tail::Gauge,
            "bull" => Tail::Bull,
            "queen" => Tail::Queen,
            "nightcap" => Tail::Nightcap,
            "wave" => Tail::Wave,
            "dragon" => Tail::Dragon,
            "ghost" => Tail::Ghost,
            "pixel-round" => Tail::PixelRound,
            "swirl" => Tail::Swirl,
            "swoop" => Tail::Swoop,
            "rattle" => Tail::Rattle,
            "rocket" => Tail::Rocket,
            "offroad" => Tail::Offroad,
            "shiny" => Tail::Shiny,
            "alligator" => Tail::Alligator,
            "comet" => Tail::Comet,
            "fish" => Tail::Fish,
            "flame" => Tail::Flame,
            "football" => Tail::Football,
            "iguana" => Tail::Iguana,
            "ion" => Tail::Ion,
            "missile" => Tail::Missile,
            "skinny-jeans" => Tail::SkinnyJeans,
            "snail" => Tail::Snail,
            "tire" => Tail::Tire,
            "virus" => Tail::Virus,
            "coffee" => Tail::Coffee,
            "mouse" => Tail::Mouse,
            "tiger-tail" => Tail::TigerTail,
            "weight" => Tail::Weight,
            "leaf" => Tail::Leaf,
            "pumpkin" => Tail::Pumpkin,
            "bonhomme" => Tail::Bonhomme,
            "flake" => Tail::Flake,
            "ice-skate" => Tail::IceSkate,
            "present" => Tail::Present,
            _ => return None,
        })
    }

    pub fn def(self) -> CustomizationDef {
        match self {
            Tail::Default => CustomizationDef {
                display_name: "Default",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::BlockBum => CustomizationDef {
                display_name: "Block Bum",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::Bolt => CustomizationDef {
                display_name: "Bolt",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::Curled => CustomizationDef {
                display_name: "Curled",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::FatRattle => CustomizationDef {
                display_name: "Fat Rattle",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::Freckled => CustomizationDef {
                display_name: "Freckled",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::Hook => CustomizationDef {
                display_name: "Hook",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::Pixel => CustomizationDef {
                display_name: "Pixel",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::RoundBum => CustomizationDef {
                display_name: "Round Bum",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::Sharp => CustomizationDef {
                display_name: "Sharp",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::Skinny => CustomizationDef {
                display_name: "Skinny",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::SmallRattle => CustomizationDef {
                display_name: "Small Rattle",
                description: "",
                group: Group::Standard,
                cost: 0,
                image_override: None,
            },
            Tail::DoSammy => CustomizationDef {
                display_name: "DigitalOcean Sammy",
                description: "Provided by DigitalOcean for the 2022 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Tail::RbcNecktie => CustomizationDef {
                display_name: "RBC Necktie",
                description: "Provided by RBC for the 2021 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Tail::ReplitNotmark => CustomizationDef {
                display_name: "Replit Not Mark",
                description: "Provided by Replit.com for the 2021 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Tail::MlhGene => CustomizationDef {
                display_name: "MLH",
                description: "Provided by Major League Hacking for the 2022 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Tail::NrBooster => CustomizationDef {
                display_name: "New Relic Booster",
                description: "Provided by New Relic for the 2022 Competitive Season",
                group: Group::PartnerBrands,
                cost: 0,
                image_override: None,
            },
            Tail::MysticMoon => CustomizationDef {
                display_name: "House of Aileen's Crescent Moon",
                description: "Created when the House of Aileen won the 2021 Summer Casters Crown tournament",
                group: Group::Community,
                cost: 0,
                image_override: None,
            },
            Tail::CrystalPower => CustomizationDef {
                display_name: "Crystal Power",
                description: "Created after the House of Aileen won the 2021 Summer Casters Crown tournament",
                group: Group::Community,
                cost: 200,
                image_override: None,
            },
            Tail::CosmicHorror => CustomizationDef {
                display_name: "Cosmic Horror",
                description: "Created for JonathanArns for winning the Spring Caster Cup 2022 tournament",
                group: Group::Community,
                cost: 200,
                image_override: None,
            },
            Tail::BeachPuffin => CustomizationDef {
                display_name: "Puffin",
                description: "Created for coreya for winning the Spring League 2022 People's Choice Award",
                group: Group::Community,
                cost: 200,
                image_override: None,
            },
            Tail::Pirate => CustomizationDef {
                display_name: "Pirate",
                description: "Created for jlafayette for winning the Summer League 2022 People's Choice Award!",
                group: Group::Community,
                cost: 200,
                image_override: None,
            },
            Tail::BeachPuffinSpecial => CustomizationDef {
                display_name: "Puffin - Special Edition",
                description: "Created for coreya for winning the Spring League 2022 People's Choice Award",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Tail::Hydra => CustomizationDef {
                display_name: "Community Hydra",
                description: "Created for anyone who is a recognized Community Contributor to the Battlesnake ecosystem",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Tail::PirateSpecial => CustomizationDef {
                display_name: "Pirate - Special Edition",
                description: "Created for jlafayette for winning the Summer League 2022 People's Choice Award!",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Tail::Goldfish => CustomizationDef {
                display_name: "Goldfish",
                description: "",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: None,
            },
            Tail::PruzzeSpecial => CustomizationDef {
                display_name: "Prüzze Coffee - Special Edition",
                description: "Created for Prüzze as a thank you for being a long term Battlesnake competitor!",
                group: Group::SpecialEdition,
                cost: 1000,
                image_override: Some(
                    "https://media.battlesnake.com/snakes/tails/pirate-special.svg",
                ),
            },
            Tail::Turtle => CustomizationDef {
                display_name: "Turtle",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Tail::Judge => CustomizationDef {
                display_name: "Judge",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Tail::Monkey => CustomizationDef {
                display_name: "Monkey",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Tail::Subway => CustomizationDef {
                display_name: "Subway",
                description: "",
                group: Group::Collection2024,
                cost: 200,
                image_override: None,
            },
            Tail::Antelope => CustomizationDef {
                display_name: "Antelope",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Rose => CustomizationDef {
                display_name: "Rose",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Chicken => CustomizationDef {
                display_name: "Chicken",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Egg => CustomizationDef {
                display_name: "Egg",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::PopStar => CustomizationDef {
                display_name: "Pop Star",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Ferret => CustomizationDef {
                display_name: "Ferret",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Flytrap => CustomizationDef {
                display_name: "Flytrap",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Submarine => CustomizationDef {
                display_name: "Submarine",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Bee => CustomizationDef {
                display_name: "Bee",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Horse => CustomizationDef {
                display_name: "Horse",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Chef => CustomizationDef {
                display_name: "Chef",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Ladybug => CustomizationDef {
                display_name: "Ladybug",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Pig => CustomizationDef {
                display_name: "Pig",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Guitar => CustomizationDef {
                display_name: "Guitar",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Train => CustomizationDef {
                display_name: "Train",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Duck => CustomizationDef {
                display_name: "Duck",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Cat => CustomizationDef {
                display_name: "Cat",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Gauge => CustomizationDef {
                display_name: "Gauge",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Bull => CustomizationDef {
                display_name: "Bull",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Queen => CustomizationDef {
                display_name: "Queen",
                description: "",
                group: Group::Collection2023,
                cost: 200,
                image_override: None,
            },
            Tail::Nightcap => CustomizationDef {
                display_name: "Nightcap",
                description: "Released June 2022",
                group: Group::Collection2022,
                cost: 200,
                image_override: None,
            },
            Tail::Wave => CustomizationDef {
                display_name: "Wave",
                description: "Released June 2022",
                group: Group::Collection2022,
                cost: 200,
                image_override: None,
            },
            Tail::Dragon => CustomizationDef {
                display_name: "Dragon",
                description: "Released September 2022",
                group: Group::Collection2022,
                cost: 200,
                image_override: None,
            },
            Tail::Ghost => CustomizationDef {
                display_name: "Ghost",
                description: "Released for Spring League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::PixelRound => CustomizationDef {
                display_name: "Pixel Round",
                description: "Released for Spring League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Swirl => CustomizationDef {
                display_name: "Swirl",
                description: "Released for Spring League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Swoop => CustomizationDef {
                display_name: "Swoop",
                description: "Released for Spring League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Rattle => CustomizationDef {
                display_name: "Rattle",
                description: "Released for Summer League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Rocket => CustomizationDef {
                display_name: "Rocket",
                description: "Released for Summer League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Offroad => CustomizationDef {
                display_name: "Offroad",
                description: "Released for Fall League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Shiny => CustomizationDef {
                display_name: "Shiny",
                description: "Released for Fall League 2021",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Alligator => CustomizationDef {
                display_name: "Alligator",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Comet => CustomizationDef {
                display_name: "Comet",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Fish => CustomizationDef {
                display_name: "Fish",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Flame => CustomizationDef {
                display_name: "Flame",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Football => CustomizationDef {
                display_name: "Football",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Iguana => CustomizationDef {
                display_name: "Iguana",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Ion => CustomizationDef {
                display_name: "Ion",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Missile => CustomizationDef {
                display_name: "Missile",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::SkinnyJeans => CustomizationDef {
                display_name: "Skinny Jeans",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Snail => CustomizationDef {
                display_name: "Snail",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Tire => CustomizationDef {
                display_name: "Tire",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Virus => CustomizationDef {
                display_name: "Virus",
                description: "2021 Battlesnake Membership Reward",
                group: Group::Collection2021,
                cost: 100,
                image_override: None,
            },
            Tail::Coffee => CustomizationDef {
                display_name: "Coffee",
                description: "Released for the Stay Home and Code 2020 compeition",
                group: Group::Collection2020,
                cost: 0,
                image_override: None,
            },
            Tail::Mouse => CustomizationDef {
                display_name: "Mouse",
                description: "Released for the Stay Home and Code 2020 compeition",
                group: Group::Collection2020,
                cost: 0,
                image_override: None,
            },
            Tail::TigerTail => CustomizationDef {
                display_name: "Tiger Tail",
                description: "Released for the Stay Home and Code 2020 compeition",
                group: Group::Collection2020,
                cost: 0,
                image_override: None,
            },
            Tail::Weight => CustomizationDef {
                display_name: "Weight",
                description: "Released for the Stay Home and Code 2020 compeition",
                group: Group::Collection2020,
                cost: 0,
                image_override: None,
            },
            Tail::Leaf => CustomizationDef {
                display_name: "Maple Leaf",
                description: "Released for Fall League 2020",
                group: Group::Collection2020,
                cost: 100,
                image_override: None,
            },
            Tail::Pumpkin => CustomizationDef {
                display_name: "Pumpkin",
                description: "Released for Fall League 2020",
                group: Group::Collection2020,
                cost: 100,
                image_override: None,
            },
            Tail::Bonhomme => CustomizationDef {
                display_name: "Bonhomme",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Tail::Flake => CustomizationDef {
                display_name: "Flake",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Tail::IceSkate => CustomizationDef {
                display_name: "Ice Skate",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
            Tail::Present => CustomizationDef {
                display_name: "Present",
                description: "Released for the Battlesnake Winter Classic 2019 tournament",
                group: Group::Collection2019,
                cost: 0,
                image_override: None,
            },
        }
    }
}
