-- Seed the customization catalog from play's authoritative data
-- (src/apps/core/management/commands/data_load_snake_customizations.py,
-- extracted 2026-07-04). Release dates were authored as US-Pacific
-- midnights; stored here as UTC (+08:00).

INSERT INTO customization_groups (slug, title, description, availability, ordinal) VALUES
    ('standard', 'Standard', 'The complete collection of all head and tail customizations.', 'everyone', 1),
    ('partner-brands', 'Partner Brands', 'Brand customizations brought to you by our wonderful partners.', 'everyone', 2),
    ('community', 'Community', 'These customizations were designed by our talented Battlesnake community.', 'restricted', 3),
    ('special-edition', 'Special Edition', 'These customizations are exclusive and cannot be unlocked with points. Instead, they are claimed with redemption codes shared on our community channels (Discord, Twitch, etc.).', 'hidden', 10),
    ('2024-collection', '2024 Collection', 'Customizations released in 2024', 'hidden', 100),
    ('2023-collection', '2023 Collection', 'Customizations released in 2023', 'restricted', 101),
    ('2022-collection', '2022 Collection', 'Customizations released in 2022', 'restricted', 102),
    ('2021-collection', '2021 Collection', 'Customizations released in 2021', 'restricted', 103),
    ('2020-collection', '2020 Collection', 'Customizations released in 2020', 'restricted', 104),
    ('2019-collection', '2019 Collection', 'Customizations released in 2019', 'everyone', 105);

INSERT INTO customizations (customization_type, slug, display_name, description, image_url, customization_group_id, cost, release_date)
SELECT v.customization_type, v.slug, v.display_name, v.description, v.image_url, g.customization_group_id, v.cost, v.release_date::timestamptz
FROM (VALUES
    ('tail', 'default', 'Default', '', 'https://media.battlesnake.com/snakes/tails/default.svg', 'standard', 0, NULL),
    ('head', 'default', 'Default', '', 'https://media.battlesnake.com/snakes/heads/default.svg', 'standard', 0, NULL),
    ('head', 'beluga', 'Beluga', '', 'https://media.battlesnake.com/snakes/heads/beluga.svg', 'standard', 0, NULL),
    ('head', 'bendr', 'Bendr', '', 'https://media.battlesnake.com/snakes/heads/bendr.svg', 'standard', 0, NULL),
    ('tail', 'block-bum', 'Block Bum', '', 'https://media.battlesnake.com/snakes/tails/block-bum.svg', 'standard', 0, NULL),
    ('tail', 'bolt', 'Bolt', '', 'https://media.battlesnake.com/snakes/tails/bolt.svg', 'standard', 0, NULL),
    ('tail', 'curled', 'Curled', '', 'https://media.battlesnake.com/snakes/tails/curled.svg', 'standard', 0, NULL),
    ('head', 'dead', 'Dead', '', 'https://media.battlesnake.com/snakes/heads/dead.svg', 'standard', 0, NULL),
    ('head', 'evil', 'Evil', '', 'https://media.battlesnake.com/snakes/heads/evil.svg', 'standard', 0, NULL),
    ('head', 'fang', 'Fang', '', 'https://media.battlesnake.com/snakes/heads/fang.svg', 'standard', 0, NULL),
    ('tail', 'fat-rattle', 'Fat Rattle', '', 'https://media.battlesnake.com/snakes/tails/fat-rattle.svg', 'standard', 0, NULL),
    ('tail', 'freckled', 'Freckled', '', 'https://media.battlesnake.com/snakes/tails/freckled.svg', 'standard', 0, NULL),
    ('tail', 'hook', 'Hook', '', 'https://media.battlesnake.com/snakes/tails/hook.svg', 'standard', 0, NULL),
    ('tail', 'pixel', 'Pixel', '', 'https://media.battlesnake.com/snakes/tails/pixel.svg', 'standard', 0, NULL),
    ('head', 'pixel', 'Pixel', '', 'https://media.battlesnake.com/snakes/heads/pixel.svg', 'standard', 0, NULL),
    ('tail', 'round-bum', 'Round Bum', '', 'https://media.battlesnake.com/snakes/tails/round-bum.svg', 'standard', 0, NULL),
    ('head', 'safe', 'Safe', '', 'https://media.battlesnake.com/snakes/heads/safe.svg', 'standard', 0, NULL),
    ('head', 'sand-worm', 'Sand Worm', '', 'https://media.battlesnake.com/snakes/heads/sand-worm.svg', 'standard', 0, NULL),
    ('head', 'shades', 'Shades', '', 'https://media.battlesnake.com/snakes/heads/shades.svg', 'standard', 0, NULL),
    ('tail', 'sharp', 'Sharp', '', 'https://media.battlesnake.com/snakes/tails/sharp.svg', 'standard', 0, NULL),
    ('head', 'silly', 'Silly', '', 'https://media.battlesnake.com/snakes/heads/silly.svg', 'standard', 0, NULL),
    ('tail', 'skinny', 'Skinny', '', 'https://media.battlesnake.com/snakes/tails/skinny.svg', 'standard', 0, NULL),
    ('tail', 'small-rattle', 'Small Rattle', '', 'https://media.battlesnake.com/snakes/tails/small-rattle.svg', 'standard', 0, NULL),
    ('head', 'smile', 'Smile', '', 'https://media.battlesnake.com/snakes/heads/smile.svg', 'standard', 0, NULL),
    ('head', 'tongue', 'Tongue', '', 'https://media.battlesnake.com/snakes/heads/tongue.svg', 'standard', 0, NULL),
    ('head', 'do-sammy', 'DigitalOcean Sammy', 'Provided by DigitalOcean for the 2022 Competitive Season', 'https://media.battlesnake.com/snakes/heads/do-sammy.svg', 'partner-brands', 0, NULL),
    ('tail', 'do-sammy', 'DigitalOcean Sammy', 'Provided by DigitalOcean for the 2022 Competitive Season', 'https://media.battlesnake.com/snakes/tails/do-sammy.svg', 'partner-brands', 0, NULL),
    ('head', 'rbc-bowler', 'RBC Bowler Hat', 'Provided by RBC for the 2021 Competitive Season', 'https://media.battlesnake.com/snakes/heads/rbc-bowler.svg', 'partner-brands', 0, NULL),
    ('tail', 'rbc-necktie', 'RBC Necktie', 'Provided by RBC for the 2021 Competitive Season', 'https://media.battlesnake.com/snakes/tails/rbc-necktie.svg', 'partner-brands', 0, NULL),
    ('head', 'replit-mark', 'Replit Mark', 'Provided by Replit.com for the 2021 Competitive Season', 'https://media.battlesnake.com/snakes/heads/replit-mark.svg', 'partner-brands', 0, NULL),
    ('tail', 'replit-notmark', 'Replit Not Mark', 'Provided by Replit.com for the 2021 Competitive Season', 'https://media.battlesnake.com/snakes/tails/replit-notmark.svg', 'partner-brands', 0, NULL),
    ('head', 'mlh-gene', 'MLH', 'Provided by Major League Hacking for the 2022 Competitive Season', 'https://media.battlesnake.com/snakes/heads/mlh-gene.svg', 'partner-brands', 0, NULL),
    ('tail', 'mlh-gene', 'MLH', 'Provided by Major League Hacking for the 2022 Competitive Season', 'https://media.battlesnake.com/snakes/tails/mlh-gene.svg', 'partner-brands', 0, NULL),
    ('head', 'nr-rocket', 'New Relic Rocket Capsule', 'Provided by New Relic for the 2022 Competitive Season', 'https://media.battlesnake.com/snakes/heads/nr-rocket.svg', 'partner-brands', 0, NULL),
    ('tail', 'nr-booster', 'New Relic Booster', 'Provided by New Relic for the 2022 Competitive Season', 'https://media.battlesnake.com/snakes/tails/nr-booster.svg', 'partner-brands', 0, NULL),
    ('tail', 'mystic-moon', 'House of Aileen''s Crescent Moon', 'Created when the House of Aileen won the 2021 Summer Casters Crown tournament', 'https://media.battlesnake.com/snakes/tails/mystic-moon.svg', 'community', 0, NULL),
    ('head', 'all-seeing', 'House of Aileen''s Magic Eye', 'Created when the House of Aileen won the 2021 Summer Caster Crown tournament', 'https://media.battlesnake.com/snakes/heads/all-seeing.svg', 'community', 0, NULL),
    ('head', 'smart-caterpillar', 'Smart Caterpillar', 'Created for user Butterfy 🦋 Tamer for winning the Summer League 2022 People''s Choice Award', 'https://media.battlesnake.com/snakes/heads/smart-caterpillar.svg', 'community', 0, NULL),
    ('head', 'trans-rights-scarf', 'Trans Rights Scarf', 'Created for user penelopezone for winning the Fall League 2022 People''s Choice Award', 'https://media.battlesnake.com/snakes/heads/trans-rights-scarf.svg', 'community', 0, NULL),
    ('head', 'crystal-power', 'Crystal Power', 'Created after the House of Aileen won the 2021 Fall Casters Crown tournament', 'https://media.battlesnake.com/snakes/heads/crystal-power.svg', 'community', 200, NULL),
    ('tail', 'crystal-power', 'Crystal Power', 'Created after the House of Aileen won the 2021 Summer Casters Crown tournament', 'https://media.battlesnake.com/snakes/tails/crystal-power.svg', 'community', 200, NULL),
    ('tail', 'cosmic-horror', 'Cosmic Horror', 'Created for JonathanArns for winning the Spring Caster Cup 2022 tournament', 'https://media.battlesnake.com/snakes/tails/cosmic-horror.svg', 'community', 200, NULL),
    ('head', 'cosmic-horror', 'Cosmic Horror', 'Created for JonathanArns for winning the Spring Caster Cup 2022 tournament', 'https://media.battlesnake.com/snakes/heads/cosmic-horror.svg', 'community', 200, NULL),
    ('head', 'beach-puffin', 'Puffin', 'Created for coreya for winning the Spring League 2022 People''s Choice Award', 'https://media.battlesnake.com/snakes/heads/beach-puffin.svg', 'community', 200, NULL),
    ('tail', 'beach-puffin', 'Puffin', 'Created for coreya for winning the Spring League 2022 People''s Choice Award', 'https://media.battlesnake.com/snakes/tails/beach-puffin.svg', 'community', 200, NULL),
    ('head', 'pirate', 'Pirate', 'Created for jlafayette for winning the Summer League 2022 People''s Choice Award!', 'https://media.battlesnake.com/snakes/heads/pirate.svg', 'community', 200, NULL),
    ('tail', 'pirate', 'Pirate', 'Created for jlafayette for winning the Summer League 2022 People''s Choice Award!', 'https://media.battlesnake.com/snakes/tails/pirate.svg', 'community', 200, NULL),
    ('head', 'cosmic-horror-special', 'Cosmic Horror - Special Edition', 'Created for jonathanarns for winning the 2022 Spring Caster Cup tournament', 'https://media.battlesnake.com/snakes/heads/cosmic-horror-special.svg', 'special-edition', 1000, NULL),
    ('head', 'beach-puffin-special', 'Puffin - Special Edition', 'Created for coreya for winning the Spring League 2022 People''s Choice Award', 'https://media.battlesnake.com/snakes/heads/beach-puffin-special.svg', 'special-edition', 1000, NULL),
    ('tail', 'beach-puffin-special', 'Puffin - Special Edition', 'Created for coreya for winning the Spring League 2022 People''s Choice Award', 'https://media.battlesnake.com/snakes/tails/beach-puffin-special.svg', 'special-edition', 1000, NULL),
    ('head', 'hydra', 'Community Hydra', 'Created for anyone who is a recognized Community Contributor to the Battlesnake ecosystem', 'https://media.battlesnake.com/snakes/heads/hydra.svg', 'special-edition', 1000, NULL),
    ('tail', 'hydra', 'Community Hydra', 'Created for anyone who is a recognized Community Contributor to the Battlesnake ecosystem', 'https://media.battlesnake.com/snakes/tails/hydra.svg', 'special-edition', 1000, NULL),
    ('head', 'pirate-special', 'Pirate - Special Edition', 'Created for jlafayette for winning the Summer League 2022 People''s Choice Award!', 'https://media.battlesnake.com/snakes/heads/pirate-special.svg', 'special-edition', 1000, NULL),
    ('tail', 'pirate-special', 'Pirate - Special Edition', 'Created for jlafayette for winning the Summer League 2022 People''s Choice Award!', 'https://media.battlesnake.com/snakes/tails/pirate-special.svg', 'special-edition', 1000, NULL),
    ('tail', 'goldfish', 'Goldfish', '', 'https://media.battlesnake.com/snakes/tails/goldfish.svg', 'special-edition', 1000, NULL),
    ('head', 'fish', 'Fish', '', 'https://media.battlesnake.com/snakes/heads/fish.svg', 'special-edition', 1000, NULL),
    ('head', 'pruzze-special', 'Prüzze Gamer - Special Edition', 'Created for Prüzze as a thank you for being a long term Battlesnake competitor!', 'https://media.battlesnake.com/snakes/heads/pirate-special.svg', 'special-edition', 1000, NULL),
    ('tail', 'pruzze-special', 'Prüzze Coffee - Special Edition', 'Created for Prüzze as a thank you for being a long term Battlesnake competitor!', 'https://media.battlesnake.com/snakes/tails/pirate-special.svg', 'special-edition', 1000, NULL),
    ('head', 'turtle', 'Turtle', '', 'https://media.battlesnake.com/snakes/heads/turtle.svg', '2024-collection', 200, '2024-01-01T08:00:00Z'),
    ('tail', 'turtle', 'Turtle', '', 'https://media.battlesnake.com/snakes/tails/turtle.svg', '2024-collection', 200, '2024-01-01T08:00:00Z'),
    ('head', 'judge', 'Judge', '', 'https://media.battlesnake.com/snakes/heads/judge.svg', '2024-collection', 200, '2024-01-01T08:00:00Z'),
    ('tail', 'judge', 'Judge', '', 'https://media.battlesnake.com/snakes/tails/judge.svg', '2024-collection', 200, '2024-01-01T08:00:00Z'),
    ('head', 'monkey', 'Monkey', '', 'https://media.battlesnake.com/snakes/heads/monkey.svg', '2024-collection', 200, '2024-02-01T08:00:00Z'),
    ('tail', 'monkey', 'Monkey', '', 'https://media.battlesnake.com/snakes/tails/monkey.svg', '2024-collection', 200, '2024-02-01T08:00:00Z'),
    ('head', 'subway', 'Subway', '', 'https://media.battlesnake.com/snakes/heads/subway.svg', '2024-collection', 200, '2024-02-01T08:00:00Z'),
    ('tail', 'subway', 'Subway', '', 'https://media.battlesnake.com/snakes/tails/subway.svg', '2024-collection', 200, '2024-02-01T08:00:00Z'),
    ('head', 'frog', 'Frog', '', 'https://media.battlesnake.com/snakes/heads/frog.svg', '2024-collection', 200, '2024-02-01T08:00:00Z'),
    ('head', 'antelope', 'Antelope', '', 'https://media.battlesnake.com/snakes/heads/antelope.svg', '2023-collection', 200, '2023-01-01T08:00:00Z'),
    ('tail', 'antelope', 'Antelope', '', 'https://media.battlesnake.com/snakes/tails/antelope.svg', '2023-collection', 200, '2023-01-01T08:00:00Z'),
    ('head', 'glasses', 'Glasses', '', 'https://media.battlesnake.com/snakes/heads/glasses.svg', '2023-collection', 200, '2023-01-01T08:00:00Z'),
    ('head', 'rose', 'Rose', '', 'https://media.battlesnake.com/snakes/heads/rose.svg', '2023-collection', 200, '2023-02-01T08:00:00Z'),
    ('tail', 'rose', 'Rose', '', 'https://media.battlesnake.com/snakes/tails/rose.svg', '2023-collection', 200, '2023-02-01T08:00:00Z'),
    ('head', 'bird', 'Bird', '', 'https://media.battlesnake.com/snakes/heads/bird.svg', '2023-collection', 200, '2023-02-01T08:00:00Z'),
    ('head', 'chicken', 'Chicken', '', 'https://media.battlesnake.com/snakes/heads/chicken.svg', '2023-collection', 200, '2023-03-01T08:00:00Z'),
    ('tail', 'chicken', 'Chicken', '', 'https://media.battlesnake.com/snakes/tails/chicken.svg', '2023-collection', 200, '2023-03-01T08:00:00Z'),
    ('head', 'egg', 'Egg', '', 'https://media.battlesnake.com/snakes/heads/egg.svg', '2023-collection', 200, '2023-03-01T08:00:00Z'),
    ('tail', 'egg', 'Egg', '', 'https://media.battlesnake.com/snakes/tails/egg.svg', '2023-collection', 200, '2023-03-01T08:00:00Z'),
    ('head', 'pop-star', 'Pop-Star', '', 'https://media.battlesnake.com/snakes/heads/pop-star.svg', '2023-collection', 200, '2023-04-01T08:00:00Z'),
    ('tail', 'pop-star', 'Pop Star', '', 'https://media.battlesnake.com/snakes/tails/pop-star.svg', '2023-collection', 200, '2023-04-01T08:00:00Z'),
    ('head', 'singer', 'Singer', '', 'https://media.battlesnake.com/snakes/heads/singer.svg', '2023-collection', 200, '2023-04-01T08:00:00Z'),
    ('head', 'ferret', 'Ferret', '', 'https://media.battlesnake.com/snakes/heads/ferret.svg', '2023-collection', 200, '2023-04-01T08:00:00Z'),
    ('tail', 'ferret', 'Ferret', '', 'https://media.battlesnake.com/snakes/tails/ferret.svg', '2023-collection', 200, '2023-04-01T08:00:00Z'),
    ('head', 'flytrap', 'Flytrap', '', 'https://media.battlesnake.com/snakes/heads/flytrap.svg', '2023-collection', 200, '2023-05-01T08:00:00Z'),
    ('tail', 'flytrap', 'Flytrap', '', 'https://media.battlesnake.com/snakes/tails/flytrap.svg', '2023-collection', 200, '2023-05-01T08:00:00Z'),
    ('head', 'submarine', 'Submarine', '', 'https://media.battlesnake.com/snakes/heads/submarine.svg', '2023-collection', 200, '2023-05-01T08:00:00Z'),
    ('tail', 'submarine', 'Submarine', '', 'https://media.battlesnake.com/snakes/tails/submarine.svg', '2023-collection', 200, '2023-05-01T08:00:00Z'),
    ('head', 'baseball', 'Baseball', '', 'https://media.battlesnake.com/snakes/heads/baseball.svg', '2023-collection', 200, '2023-06-01T08:00:00Z'),
    ('head', 'bee', 'Bee', '', 'https://media.battlesnake.com/snakes/heads/bee.svg', '2023-collection', 200, '2023-06-01T08:00:00Z'),
    ('tail', 'bee', 'Bee', '', 'https://media.battlesnake.com/snakes/tails/bee.svg', '2023-collection', 200, '2023-06-01T08:00:00Z'),
    ('head', 'horse', 'Horse', '', 'https://media.battlesnake.com/snakes/heads/horse.svg', '2023-collection', 200, '2023-06-01T08:00:00Z'),
    ('tail', 'horse', 'Horse', '', 'https://media.battlesnake.com/snakes/tails/horse.svg', '2023-collection', 200, '2023-06-01T08:00:00Z'),
    ('head', 'chef', 'Chef', '', 'https://media.battlesnake.com/snakes/heads/chef.svg', '2023-collection', 200, '2023-07-01T08:00:00Z'),
    ('tail', 'chef', 'Chef', '', 'https://media.battlesnake.com/snakes/tails/chef.svg', '2023-collection', 200, '2023-07-01T08:00:00Z'),
    ('head', 'ladybug', 'Ladybug', '', 'https://media.battlesnake.com/snakes/heads/ladybug.svg', '2023-collection', 200, '2023-07-01T08:00:00Z'),
    ('tail', 'ladybug', 'Ladybug', '', 'https://media.battlesnake.com/snakes/tails/ladybug.svg', '2023-collection', 200, '2023-07-01T08:00:00Z'),
    ('head', 'pig', 'Pig', '', 'https://media.battlesnake.com/snakes/heads/pig.svg', '2023-collection', 200, '2023-08-01T08:00:00Z'),
    ('tail', 'pig', 'Pig', '', 'https://media.battlesnake.com/snakes/tails/pig.svg', '2023-collection', 200, '2023-08-01T08:00:00Z'),
    ('head', 'guitar', 'Guitar', '', 'https://media.battlesnake.com/snakes/heads/guitar.svg', '2023-collection', 200, '2023-08-01T08:00:00Z'),
    ('tail', 'guitar', 'Guitar', '', 'https://media.battlesnake.com/snakes/tails/guitar.svg', '2023-collection', 200, '2023-08-01T08:00:00Z'),
    ('head', 'train', 'Train', '', 'https://media.battlesnake.com/snakes/heads/train.svg', '2023-collection', 200, '2023-09-01T08:00:00Z'),
    ('tail', 'train', 'Train', '', 'https://media.battlesnake.com/snakes/tails/train.svg', '2023-collection', 200, '2023-09-01T08:00:00Z'),
    ('head', 'duck', 'Duck', '', 'https://media.battlesnake.com/snakes/heads/duck.svg', '2023-collection', 200, '2023-09-01T08:00:00Z'),
    ('tail', 'duck', 'Duck', '', 'https://media.battlesnake.com/snakes/tails/duck.svg', '2023-collection', 200, '2023-09-01T08:00:00Z'),
    ('head', 'ghost', 'Ghost', '', 'https://media.battlesnake.com/snakes/heads/ghost.svg', '2023-collection', 200, '2023-10-01T08:00:00Z'),
    ('head', 'knight', 'Knight', '', 'https://media.battlesnake.com/snakes/heads/knight.svg', '2023-collection', 200, '2023-10-01T08:00:00Z'),
    ('head', 'superhero', 'Superhero', '', 'https://media.battlesnake.com/snakes/heads/superhero.svg', '2023-collection', 200, '2023-10-01T08:00:00Z'),
    ('head', 'top-hat', 'Top Hat', '', 'https://media.battlesnake.com/snakes/heads/top-hat.svg', '2023-collection', 200, '2023-10-01T08:00:00Z'),
    ('head', 'cat', 'Cat', '', 'https://media.battlesnake.com/snakes/heads/cat.svg', '2023-collection', 200, '2023-11-01T08:00:00Z'),
    ('tail', 'cat', 'Cat', '', 'https://media.battlesnake.com/snakes/tails/cat.svg', '2023-collection', 200, '2023-11-01T08:00:00Z'),
    ('head', 'drill', 'Drill', '', 'https://media.battlesnake.com/snakes/heads/drill.svg', '2023-collection', 200, '2023-11-01T08:00:00Z'),
    ('tail', 'gauge', 'Gauge', '', 'https://media.battlesnake.com/snakes/tails/gauge.svg', '2023-collection', 200, '2023-11-01T08:00:00Z'),
    ('head', 'bull', 'Bull', '', 'https://media.battlesnake.com/snakes/heads/bull.svg', '2023-collection', 200, '2023-12-01T08:00:00Z'),
    ('tail', 'bull', 'Bull', '', 'https://media.battlesnake.com/snakes/tails/bull.svg', '2023-collection', 200, '2023-12-01T08:00:00Z'),
    ('head', 'queen', 'Queen', '', 'https://media.battlesnake.com/snakes/heads/queen.svg', '2023-collection', 200, '2023-12-01T08:00:00Z'),
    ('tail', 'queen', 'Queen', '', 'https://media.battlesnake.com/snakes/tails/queen.svg', '2023-collection', 200, '2023-12-01T08:00:00Z'),
    ('head', 'eel', 'Eel', 'Released June 2022', 'https://media.battlesnake.com/snakes/heads/eel.svg', '2022-collection', 200, NULL),
    ('tail', 'nightcap', 'Nightcap', 'Released June 2022', 'https://media.battlesnake.com/snakes/tails/nightcap.svg', '2022-collection', 200, NULL),
    ('head', 'shark', 'Shark', 'Released June 2022', 'https://media.battlesnake.com/snakes/heads/shark.svg', '2022-collection', 200, NULL),
    ('head', 'sleepy', 'Sleepy', 'Released June 2022', 'https://media.battlesnake.com/snakes/heads/sleepy.svg', '2022-collection', 200, NULL),
    ('tail', 'wave', 'Wave', 'Released June 2022', 'https://media.battlesnake.com/snakes/tails/wave.svg', '2022-collection', 200, NULL),
    ('head', 'dragon', 'Dragon', 'Released September 2022', 'https://media.battlesnake.com/snakes/heads/dragon.svg', '2022-collection', 200, NULL),
    ('tail', 'dragon', 'Dragon', 'Released September 2022', 'https://media.battlesnake.com/snakes/tails/dragon.svg', '2022-collection', 200, NULL),
    ('head', 'cute-dragon', 'Cute-Dragon', 'Released September 2022', 'https://media.battlesnake.com/snakes/heads/cute-dragon.svg', '2022-collection', 200, NULL),
    ('head', 'chomp', 'Chomp', 'Released for Spring League 2021', 'https://media.battlesnake.com/snakes/heads/chomp.svg', '2021-collection', 100, NULL),
    ('tail', 'ghost', 'Ghost', 'Released for Spring League 2021', 'https://media.battlesnake.com/snakes/tails/ghost.svg', '2021-collection', 100, NULL),
    ('head', 'orca', 'Orca', 'Released for Spring League 2021', 'https://media.battlesnake.com/snakes/heads/orca.svg', '2021-collection', 100, NULL),
    ('tail', 'pixel-round', 'Pixel Round', 'Released for Spring League 2021', 'https://media.battlesnake.com/snakes/tails/pixel-round.svg', '2021-collection', 100, NULL),
    ('head', 'pixel-round', 'Pixel Round', 'Released for Spring League 2021', 'https://media.battlesnake.com/snakes/heads/pixel-round.svg', '2021-collection', 100, NULL),
    ('head', 'sneaky', 'Sneaky', 'Released for Spring League 2021', 'https://media.battlesnake.com/snakes/heads/sneaky.svg', '2021-collection', 100, NULL),
    ('tail', 'swirl', 'Swirl', 'Released for Spring League 2021', 'https://media.battlesnake.com/snakes/tails/swirl.svg', '2021-collection', 100, NULL),
    ('tail', 'swoop', 'Swoop', 'Released for Spring League 2021', 'https://media.battlesnake.com/snakes/tails/swoop.svg', '2021-collection', 100, NULL),
    ('tail', 'rattle', 'Rattle', 'Released for Summer League 2021', 'https://media.battlesnake.com/snakes/tails/rattle.svg', '2021-collection', 100, NULL),
    ('tail', 'rocket', 'Rocket', 'Released for Summer League 2021', 'https://media.battlesnake.com/snakes/tails/rocket.svg', '2021-collection', 100, NULL),
    ('head', 'villain', 'Villain', 'Released for Summer League 2021', 'https://media.battlesnake.com/snakes/heads/villain.svg', '2021-collection', 100, NULL),
    ('head', 'viper', 'Viper', 'Released for Summer League 2021', 'https://media.battlesnake.com/snakes/heads/rattler.svg', '2021-collection', 100, NULL),
    ('head', 'happy', 'Happy', 'Released for Fall League 2021', 'https://media.battlesnake.com/snakes/heads/happy.svg', '2021-collection', 100, NULL),
    ('tail', 'offroad', 'Offroad', 'Released for Fall League 2021', 'https://media.battlesnake.com/snakes/tails/offroad.svg', '2021-collection', 100, NULL),
    ('tail', 'shiny', 'Shiny', 'Released for Fall League 2021', 'https://media.battlesnake.com/snakes/tails/shiny.svg', '2021-collection', 100, NULL),
    ('head', 'whale', 'Whale', 'Released for Fall League 2021', 'https://media.battlesnake.com/snakes/heads/whale.svg', '2021-collection', 100, NULL),
    ('tail', 'alligator', 'Alligator', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/alligator.svg', '2021-collection', 100, NULL),
    ('head', 'alligator', 'Alligator', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/alligator.svg', '2021-collection', 100, NULL),
    ('head', 'comet', 'Comet', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/comet.svg', '2021-collection', 100, NULL),
    ('tail', 'comet', 'Comet', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/comet.svg', '2021-collection', 100, NULL),
    ('tail', 'fish', 'Fish', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/fish.svg', '2021-collection', 100, NULL),
    ('tail', 'flame', 'Flame', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/flame.svg', '2021-collection', 100, NULL),
    ('head', 'football', 'Football', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/football.svg', '2021-collection', 100, NULL),
    ('tail', 'football', 'Football', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/football.svg', '2021-collection', 100, NULL),
    ('tail', 'iguana', 'Iguana', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/iguana.svg', '2021-collection', 100, NULL),
    ('head', 'iguana', 'Iguana', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/iguana.svg', '2021-collection', 100, NULL),
    ('tail', 'ion', 'Ion', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/ion.svg', '2021-collection', 100, NULL),
    ('head', 'lantern-fish', 'Lantern Fish', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/lantern-fish.svg', '2021-collection', 100, NULL),
    ('head', 'mask', 'Mask', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/mask.svg', '2021-collection', 100, NULL),
    ('tail', 'missile', 'Missile', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/missile.svg', '2021-collection', 100, NULL),
    ('head', 'missile', 'Missile', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/missile.svg', '2021-collection', 100, NULL),
    ('head', 'moto-helmet', 'Moto Helmet', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/moto-helmet.svg', '2021-collection', 100, NULL),
    ('head', 'moustache', 'Moustache', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/moustache.svg', '2021-collection', 100, NULL),
    ('head', 'rocket-helmet', 'Rocket Helmet', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/rocket-helmet.svg', '2021-collection', 100, NULL),
    ('tail', 'skinny-jeans', 'Skinny Jeans', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/skinny-jeans.svg', '2021-collection', 100, NULL),
    ('head', 'snail', 'Snail', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/snail.svg', '2021-collection', 100, NULL),
    ('tail', 'snail', 'Snail', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/snail.svg', '2021-collection', 100, NULL),
    ('head', 'space-helmet', 'Space Helmet', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/heads/space-helmet.svg', '2021-collection', 100, NULL),
    ('tail', 'tire', 'Tire', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/tire.svg', '2021-collection', 100, NULL),
    ('tail', 'virus', 'Virus', '2021 Battlesnake Membership Reward', 'https://media.battlesnake.com/snakes/tails/virus.svg', '2021-collection', 100, NULL),
    ('head', 'caffeine', 'Caffeine', 'Released for the Stay Home and Code 2020 compeition', 'https://media.battlesnake.com/snakes/heads/caffeine.svg', '2020-collection', 0, NULL),
    ('tail', 'coffee', 'Coffee', 'Released for the Stay Home and Code 2020 compeition', 'https://media.battlesnake.com/snakes/tails/coffee.svg', '2020-collection', 0, NULL),
    ('head', 'gamer', 'Gamer', 'Released for the Stay Home and Code 2020 compeition', 'https://media.battlesnake.com/snakes/heads/gamer.svg', '2020-collection', 0, NULL),
    ('tail', 'mouse', 'Mouse', 'Released for the Stay Home and Code 2020 compeition', 'https://media.battlesnake.com/snakes/tails/mouse.svg', '2020-collection', 0, NULL),
    ('head', 'tiger-king', 'Tiger King', 'Released for the Stay Home and Code 2020 compeition', 'https://media.battlesnake.com/snakes/heads/tiger-king.svg', '2020-collection', 0, NULL),
    ('tail', 'tiger-tail', 'Tiger Tail', 'Released for the Stay Home and Code 2020 compeition', 'https://media.battlesnake.com/snakes/tails/tiger-tail.svg', '2020-collection', 0, NULL),
    ('tail', 'weight', 'Weight', 'Released for the Stay Home and Code 2020 compeition', 'https://media.battlesnake.com/snakes/tails/weight.svg', '2020-collection', 0, NULL),
    ('head', 'workout', 'Workout', 'Released for the Stay Home and Code 2020 compeition', 'https://media.battlesnake.com/snakes/heads/workout.svg', '2020-collection', 0, NULL),
    ('head', 'jackolantern', 'Jack O''lantern', 'Released for Fall League 2020', 'https://media.battlesnake.com/snakes/heads/jackolantern.svg', '2020-collection', 100, NULL),
    ('tail', 'leaf', 'Maple Leaf', 'Released for Fall League 2020', 'https://media.battlesnake.com/snakes/tails/leaf.svg', '2020-collection', 100, NULL),
    ('tail', 'pumpkin', 'Pumpkin', 'Released for Fall League 2020', 'https://media.battlesnake.com/snakes/tails/pumpkin.svg', '2020-collection', 100, NULL),
    ('head', 'pumpkin', 'Pumpkin', 'Released for Fall League 2020', 'https://media.battlesnake.com/snakes/heads/pumpkin.svg', '2020-collection', 100, NULL),
    ('head', 'bonhomme', 'Bonhomme', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/heads/bonhomme.svg', '2019-collection', 0, NULL),
    ('tail', 'bonhomme', 'Bonhomme', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/tails/bonhomme.svg', '2019-collection', 0, NULL),
    ('head', 'earmuffs', 'Earmuffs', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/heads/earmuffs.svg', '2019-collection', 0, NULL),
    ('tail', 'flake', 'Flake', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/tails/flake.svg', '2019-collection', 0, NULL),
    ('tail', 'ice-skate', 'Ice Skate', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/tails/ice-skate.svg', '2019-collection', 0, NULL),
    ('tail', 'present', 'Present', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/tails/present.svg', '2019-collection', 0, NULL),
    ('head', 'rudolph', 'Rudolph', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/heads/rudolph.svg', '2019-collection', 0, NULL),
    ('head', 'scarf', 'Scarf', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/heads/scarf.svg', '2019-collection', 0, NULL),
    ('head', 'ski', 'Ski', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/heads/ski.svg', '2019-collection', 0, NULL),
    ('head', 'snowman', 'Snowman', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/heads/snowman.svg', '2019-collection', 0, NULL),
    ('head', 'snow-worm', 'Snow Worm', 'Released for the Battlesnake Winter Classic 2019 tournament', 'https://media.battlesnake.com/snakes/heads/snow-worm.svg', '2019-collection', 0, NULL)
) AS v(customization_type, slug, display_name, description, image_url, group_slug, cost, release_date)
JOIN customization_groups g ON g.slug = v.group_slug;
