//! Reference heads and tails: the official Standard (free) shapes the studio pairs an
//! upload with and the guide illustrates. A static table, so nothing is processed at
//! runtime.
//!
//! Generated by processing the raw catalog SVGs vendored in
//! `server/tests/fixtures/design_kit/refs/` with [`super::process_upload`];
//! `server/tests/design_kit_refs.rs` checks the table against fresh output (and that each
//! is `VectorExact` with no warnings). To regenerate after a pipeline change:
//!
//! ```text
//! cargo test -p arena --test design_kit_refs -- --ignored --nocapture print_refs_table
//! ```
//!
//! Display names match `customizations::catalog` (checked by a test there).

use super::{AssetKind, FillRule};

/// One reference shape: a clean path in the 100x100 box.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RefShape {
    pub slug: &'static str,
    pub kind: AssetKind,
    pub display_name: &'static str,
    /// Absolute `M`/`L`/`Q`/`C`/`Z` commands, like `CleanShape::path_d`.
    pub d: &'static str,
    pub fill_rule: FillRule,
}

/// Every reference shape, heads first, in catalog order.
pub const REFS: &[RefShape] = &[
    // @generated begin
    RefShape {
        slug: "default",
        kind: AssetKind::Head,
        display_name: "Default",
        d: "M0 100L100 100L56 55.39L100 15.5L100 0.11L0 0ZM12.52 19.29C17.63 19.29 21.78 23.44 21.78 28.55C21.78 33.66 17.63 37.81 12.52 37.81C7.41 37.81 3.26 33.66 3.26 28.55C3.26 23.44 7.41 19.29 12.52 19.29Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "beluga",
        kind: AssetKind::Head,
        display_name: "Beluga",
        d: "M0 100L56 100L32 88L27 74L100 76L90 28L50 0L0 0ZM23 39C27.66 39.55 31.12 43.6 30.93 48.29C30.74 52.98 26.98 56.74 22.29 56.93C17.6 57.12 13.55 53.66 13 49C12.67 46.26 13.62 43.52 15.57 41.57C17.52 39.62 20.26 38.67 23 39Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "bendr",
        kind: AssetKind::Head,
        display_name: "Bendr",
        d: "M25.91 21.49C26.1 21.49 26.3 21.51 26.49 21.54C22.7 17.84 16.64 17.89 12.91 21.65C9.19 25.41 9.19 31.47 12.91 35.23C16.64 38.99 22.7 39.04 26.49 35.34C26.3 35.37 26.1 35.39 25.91 35.39C23.16 35.39 21.01 32.34 21.01 28.44C21.01 24.54 23.16 21.49 25.91 21.49ZM100 43.78L100 35.08C100 15.75 84.33 0.08 65 0.08L0 0L0 100L65.6 100C84.09 100 98.6 89.66 99.83 71.5L92.59 71.5L92.59 43.78ZM19.78 41.08C14.67 41.08 10.05 38.01 8.1 33.28C6.14 28.56 7.21 23.12 10.83 19.51C14.44 15.89 19.88 14.81 24.6 16.76C29.33 18.72 32.41 23.33 32.41 28.44C32.4 35.41 26.75 41.07 19.78 41.08ZM50 57.64C50 51.35 54.25 45.85 60.33 44.25L60.33 71C54.26 69.4 50.02 63.92 50 57.64ZM64.6 71.5L64.6 43.78L74.34 43.78L74.34 71.5ZM88.33 71.5L78.59 71.5L78.59 43.78L88.33 43.78Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "evil",
        kind: AssetKind::Head,
        display_name: "Evil",
        d: "M100 41L100 14L0 0L0 100L74 100C44 90 32 82 26 64C58 63 81 51 100 41ZM26 41C22.41 44.59 16.59 44.59 13 41C9.41 37.41 9.41 31.59 13 28C14 27 27 40 26 41ZM29 32L6 9L42 31L38 33C35.16 34.91 31.35 34.49 29 32Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "fang",
        kind: AssetKind::Head,
        display_name: "Fang",
        d: "M92.11 43.77L91.77 42.35C90.39 36.73 87.23 31.71 82.77 28.03L93.45 21.7L94.6 26.52C95.44 29.69 95.41 33.03 94.52 36.19ZM0 0L100 0.11L100 15.5L56 55.39L100 100L0 100ZM21.78 28.55C21.78 23.44 17.63 19.29 12.52 19.29C7.41 19.29 3.26 23.44 3.26 28.55C3.26 33.66 7.41 37.81 12.52 37.81C17.63 37.81 21.78 33.66 21.78 28.55Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "smile",
        kind: AssetKind::Head,
        display_name: "Smile",
        d: "M75.58 58.33L64 69.91L53.42 59.33L46 59.33L43.83 57.33L54.25 57.33L64 67.09L74.75 56.33L100 56.33L100 28.55L0 0L0 100L100 77.67L100 58.33ZM12.52 37.8C7.41 37.8 3.26 33.65 3.26 28.54C3.26 23.43 7.41 19.28 12.52 19.28C17.63 19.28 21.78 23.43 21.78 28.54C21.78 33.65 17.63 37.8 12.52 37.8Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "pixel",
        kind: AssetKind::Head,
        display_name: "Pixel",
        d: "M89.51 36.5L89.38 36.5L89.38 36.63L89.51 36.5ZM78.85 47.12L78.76 47.12L78.76 47.2L78.85 47.12ZM0 100L89.38 100.07L89.38 89.45L89.24 89.31L78.76 89.31L78.76 78.9L78.55 78.69L68.14 78.69L68.14 68.55L57.52 68.38L57.52 57.74L68.14 57.74L68.14 47.12L78.76 47.12L78.76 36.5L89.38 36.5L89.38 25.88L100 25.88L100 0.11L0 0ZM5 20.33L20.4 20.33L20.4 35.73L5 35.73Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "sand-worm",
        kind: AssetKind::Head,
        display_name: "Sand Worm",
        d: "M73.01 85.04L92.19 75.17L72.77 65.17L55.04 75.04L73.01 85.04ZM73.12 35.04L92.27 25.17L72.81 15.13L55.07 25L73.12 35.04ZM100 50L73.12 35.04L55.07 25L72.81 15.13L100 0L0 0L0 100.07L100 100.07L73.01 85.04L55.04 75.04L72.77 65.17L100 50Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "tongue",
        kind: AssetKind::Head,
        display_name: "Tongue",
        d: "M88 57L99 46C100.38 44.9 100.6 42.88 99.5 41.5C98.4 40.12 96.38 39.9 95 41L82 54L43 54L91 16L91 0L0 0L0 100L89 100L44 60L82 60L95 73C96.38 74.1 98.4 73.88 99.5 72.5C100.6 71.12 100.38 69.1 99 68ZM13 38C8.2 37.46 4.68 33.23 5.02 28.41C5.37 23.59 9.47 19.9 14.3 20.06C19.13 20.22 22.97 24.17 23 29C23.02 31.57 21.93 34.03 20.02 35.75C18.11 37.47 15.55 38.29 13 38Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "default",
        kind: AssetKind::Tail,
        display_name: "Default",
        d: "M50 0L0 0L0 100L50 100L100 50L50 0Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "curled",
        kind: AssetKind::Tail,
        display_name: "Curled",
        d: "M23 48C25 60 25 74 27 74C27 74 25 74 27 74C29 74 28 55 26 46C25 36 24 27 25 18C26 9 31 1 42 0C52 -1 61 5 67 12C72 19 74 23 75 33L76 45C76 48 74 62 75 66C76 71 83 73 83 73C91 76 99 72 100 74C100 76 97 79 92 80C81 83 68 86 62 76C58 68 60 58 60 50C59 41 59 30 54 22C52 19 48 17 45 18C42 19 43 22 43 24C43 44 52 66 45 85C41 93 34 101 24 100L20 99L18 98C15 96 12 96 9 96C5 97 4 100 0 100L0 0C17 2 22 38 23 48Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "bolt",
        kind: AssetKind::Tail,
        display_name: "Bolt",
        d: "M0 100L36 70L36 88L100 66L60 63L61 45L0 0L0 100Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "round-bum",
        kind: AssetKind::Tail,
        display_name: "Round Bum",
        d: "M100 28.5C98.75 10.5 84 0 65 0L0 0L0 100L65 100C83.5 100 100 90 100 71.5L100 28.5Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "hook",
        kind: AssetKind::Tail,
        display_name: "Hook",
        d: "M0 0L32 40L67 61L85 35L71 10L99 33L87 87L53 95L0 100L0 0Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "block-bum",
        kind: AssetKind::Tail,
        display_name: "Block Bum",
        d: "M0 0L100 0L100 100L0 100Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "sharp",
        kind: AssetKind::Tail,
        display_name: "Sharp",
        d: "M0 0L100 50L0 100L0 0Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "pixel",
        kind: AssetKind::Tail,
        display_name: "Pixel",
        d: "M55 0L55 11L67 11L67 22L78 22L78 33L89 33L89 45L100 45L100 56L89 56L89 66L78 66L78 78L67 78L67 89L56 89L56 100L0 100L0 0L55 0ZM5 81Z",
        fill_rule: FillRule::NonZero,
    },
    RefShape {
        slug: "freckled",
        kind: AssetKind::Tail,
        display_name: "Freckled",
        d: "M100 50C100 77 79 99 52 100L0 100L0 0L52 0C79 1 100 23 100 50ZM56 24C57 28 60 30 64 30C67.87 29.17 70.33 25.37 69.5 21.5C68.67 17.63 64.87 15.17 61 16C57 17 55 21 56 24ZM65 38C64 34 60 32 56 33C52 34 50 38 51 41C51 45 55 48 59 47C63 46 66 42 65 38ZM81 33C80 29 77 27 73 28C69 29 67 33 67 37C68 41 72 43 76 42C80 41 82 37 81 33Z",
        fill_rule: FillRule::NonZero,
    },
    // @generated end
];

/// The reference shapes of one kind.
pub fn of_kind(kind: AssetKind) -> impl Iterator<Item = &'static RefShape> {
    REFS.iter().filter(move |r| r.kind == kind)
}

/// One reference shape by kind and slug.
pub fn find(kind: AssetKind, slug: &str) -> Option<&'static RefShape> {
    of_kind(kind).find(|r| r.slug == slug)
}
